export { default as Hero } from './hero/Hero'
export { default as BestSelling } from './best-selling/best-selling'
export { default as NewCourses } from './new-courses/new-courses'
export { default as NextCourses } from './next-courses/next-courses'
export { default as CourseCategories } from './course-categories/course-categories'
export { default as FreeCourses } from './free-courses/free-courses'
export { default as Testimonials } from './testimonials/testimonials'
export { default as Subscribe } from './subscribe/subscribe'
export { default as Countdown } from './countdown/countdown'
export { default as Discover } from './discover/discover'

